version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: npm install
      - run: npm cache clean --force
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  acceptence:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  hithere:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: echo "Hellloooo!"
  sonnguyen:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: echo "My Name is Son"
  deploypro:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: echo "Deployed"
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - sonnguyen
      - hithere:
          requires:
            - sonnguyen
          filters:
            branches:
              only:
                - develop
                - /branch-.*/
      - test:
          requires:
            - hithere
      - acceptence:
          requires:
            - build
      - deploypro:
          requires:
            - test
            - acceptence
